### ISSUE TITLE
App crashes when using HTC One (M8)

### ISSUE THREAD

**Issue by candemore1024** [Scandit/BarcodeScannerPlugin#21]
Hi,

your scanner is the best I've found, fast and reliable, thanks so much!

The plugin works perfect, but I've an issue scanning with the HTC One M8 (Android 4.4), the app crashes. I'm using Phonegap 3.6.3.

java.lang.NullPointerException
at com.scandit.base.camera.SbCameraPreview.handleAutofocusEvent(SbCameraPreview.java:276)
at com.scandit.base.camera.SbCameraPreview.onPreviewFrame(SbCameraPreview.java:464)
at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1324)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:157)
at android.app.ActivityThread.main(ActivityThread.java:5633)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
at dalvik.system.NativeStart.main(Native Method)

**Comment by moritz-scandit** [comment]
Hi, it looks like you are using one of the older libraries where this is not fixed yet, probably because the Phonegap downloadable on our website is not currently up to date. Please download the 4.3 native release or even 4.4 beta from your account page on scandit.com. You can then simply replace the library in your existing project (for android the .jar and .so files under libs/), clean the project and redeploy it.

**Comment by candemore1024** [comment]
ok thanks. I'm using the 4.2.0. I will try with the 4.3.3

**Comment by ghaiat** [comment]
Hello
Same  here. Could you upgrade the plugin with the latest SDK? it will be easier than having to do it manually
Cheers

**Comment by floerkem** [comment]
The Phonegap Plugin 4.4.1 with the latest native versions of our Scandit SDK is now available for download from your Scandit account. 

Christian

On 25 Mar 2015 at 14:15:25, ghaiat (notifications@github.com) wrote:

Hello
Same here. Could you upgrade the plugin with the latest SDK? it will be easier than having to do it manually
Cheers
